### ISSUE TITLE
[Add Module] Communications Jammer

### ISSUE THREAD

**Issue by CE-Modding** [hypoxia125/Modules-Enhanced#27]
**Module Title**
JAMMER

**Module Description**
Blocks gps / map with creation of a dead zone aka black map marker
Tfar compat would be greatly appreciated (area I the dead zone has reduced / incredibly poor comms)

**Attributes**
area of effect / size
Amount of jamming (light gray to black marker [light jamming to heavy/full blocking])

**Comment by hypoxia125** [comment]
A few ways I could go about doing this.

Map:
Opaque/%lucent map marker like you suggest or could create a PPEffect for noise that covers the map screen...
Block the map entirely
Block map use entirely

GPS:
Block creation of the display itself

Radios:
TFAR suggestion
Block/inhibit base game radio channels

Would need to make a separate compat addon for TFAR use that only shows up when TFAR is loaded.

**Comment by CE-Modding** [comment]
Honestly do it however you see fit; I prefer the idea of an effect/noise that gets worse and worse the closer you get to the area of a jammer.

**Comment by hypoxia125** [comment]
Update:

Currently have map blocking and vanilla gps blocking working

**Comment by hypoxia125** [comment]
One Issue:

TFAR does not allow for local changes in radio volume or anything that I can simulate a jamming system currently. It looks like all the effects are handled on the TS side of things now.

Edit: ACRE2 does support this so I will add a compat for that

**Comment by hypoxia125** [comment]
Added chat text scrambling as well

**Comment by hypoxia125** [comment]
Complete and merged to main #59

**Comment by hypoxia125** [comment]
Complete and merged to main #59
