### ISSUE TITLE
[Add Module] A Paradrop module that allows synched vehicles to be used for paradrop of player and AI

### ISSUE THREAD

**Issue by 6komodo6** [hypoxia125/Modules-Enhanced#68]
**Module Title**
Paradrop troop transport

**Module Description**
This module, when synched to a specific vehicle (heli/planes), will add addAction to it. When the player is in that vic along with AI in group, they can use the addAction to EJECT along with their AI group as a paradrop. They open their chutes (predetermined height in module if possible) and land. This module takes care of replacing back any backpacks they had before the jump for the player and AI

**Attributes**
Chute open height
Smoke trails the paradrop to show location or at time of touchdown
Type of chute (static or steerable)

**Comment by hypoxia125** [comment]
When you say smoke trails, you mean on each person? Or drop a smoke from the aircraft and have it land wherever it lands? Or fictional ring of smoke when the first person lands?

**Comment by hypoxia125** [comment]
Merged to 0.8.0 develop. Will release when 0.8.0 drops.

**Comment by 6komodo6** [comment]
> When you say smoke trails, you mean on each person? Or drop a smoke from the aircraft and have it land wherever it lands? Or fictional ring of smoke when the first person lands?

Yeah meant on the belt or foot of each person, for visual indication

**Comment by hypoxia125** [comment]
Yeah I can add that in a patch
