### ISSUE TITLE
[Add Module] A "Heal" module, which i think compliments the REARM and REFUEL module

### ISSUE THREAD

**Issue by 6komodo6** [hypoxia125/Modules-Enhanced#69]
**Module Title**
HEAL module

**Module Description**
Allows either synched items or area covered by the module to act as healing station for players or AI.

**Attributes**
Synch or area option
Heal parameter: Player, AI, All etc
HoldAction on item for the healing to take effect

**Comment by hypoxia125** [comment]
Will have to be vanilla only atm

**Comment by 6komodo6** [comment]
Yeah vanilla, I'm guessing ACE complicates things

**Comment by hypoxia125** [comment]
#71

linked PR. Will release with 0.8.0 when finished.

**Comment by 6komodo6** [comment]
Thnx Hypoxic appreciate it🙏🏿
