### ISSUE TITLE
[Add Module] Replace Object

### ISSUE THREAD

**Issue by Dual1Swords** [hypoxia125/Modules-Enhanced#83]
**Module Title**
Replace Object

**Module Description**
This module will replace any object with another object when you sync the object you want to replace while keeping the original object place and orientation.
You can also replace object in a layer.

**Attributes**
What object you want to replace with.
what layer if any you want the object to replace in with.

**Comment by hypoxia125** [comment]
Are you looking to have this as an editor extension to help with the placement of objects and not something that runs after mission start? If so, this is probably a better task for 3DEN Enhanced (which I can write for it, but it will probably be there, not here).

**Comment by Dual1Swords** [comment]
No, this it not meant to help with placement of object rather it changes objects from one to another. For example a player kills all the opfor at there base. Rather then going into Zeus and deleting the flag pole and placing a bluefor's one, you just say you want this flag pole to change to bluefor and have that module sync to a trigger for when opfor is no longer present.

**Comment by hypoxia125** [comment]
Hmm, maybe I can make specific things. If I open it up to whatever, then people will not use it right and then complain. Maybe I can do a "Change Flag" module or something, along with any other specific ideas.
